// -----------------------------------------------------------------------
// <copyright file="MattermostCallbackActionStore.cs" company="Petabridge, LLC">
//      Copyright (C) 2026 - 2026 Petabridge, LLC <https://petabridge.com>
// </copyright>
// -----------------------------------------------------------------------
using System.Collections.Concurrent;
using System.Security.Cryptography;

namespace Netclaw.Channels.Mattermost;

/// <summary>
/// Stores one-time opaque callback actions for Mattermost interactive approvals.
/// The token is generated by the daemon, embedded in the button context, and
/// consumed exactly once when the callback returns.
/// </summary>
public sealed class MattermostCallbackActionStore(TimeProvider timeProvider)
{
    private static readonly TimeSpan EntryLifetime = TimeSpan.FromHours(12);
    private static readonly TimeSpan CleanupInterval = TimeSpan.FromMinutes(15);

    private readonly ConcurrentDictionary<string, StoredAction> _entries = new(StringComparer.Ordinal);
    private readonly Lock _cleanupLock = new();
    private DateTimeOffset _nextCleanupAt = timeProvider.GetUtcNow().Add(CleanupInterval);

    public string CreateAction(
        string channelId,
        string callId,
        string selectedKey,
        string rootPostId,
        string? requesterSenderId)
    {
        var token = CreateToken();
        var now = timeProvider.GetUtcNow();
        var entry = new StoredAction(
            ChannelId: channelId,
            CallId: callId,
            SelectedKey: selectedKey,
            RootPostId: rootPostId,
            RequesterSenderId: requesterSenderId,
            ExpiresAt: now.Add(EntryLifetime));

        _entries[token] = entry;
        CleanupExpired(now);
        return token;
    }

    public bool TryConsume(string token, out StoredAction? action)
    {
        action = null;
        var now = timeProvider.GetUtcNow();
        CleanupExpired(now);

        if (!_entries.TryRemove(token, out var entry))
            return false;

        if (entry.ExpiresAt < now)
            return false;

        action = entry;
        return true;
    }

    public sealed record StoredAction(
        string ChannelId,
        string CallId,
        string SelectedKey,
        string RootPostId,
        string? RequesterSenderId,
        DateTimeOffset ExpiresAt);

    private static string CreateToken()
    {
        Span<byte> bytes = stackalloc byte[32];
        RandomNumberGenerator.Fill(bytes);
        return Convert.ToHexString(bytes).ToLowerInvariant();
    }

    private void CleanupExpired(DateTimeOffset now)
    {
        if (now < _nextCleanupAt)
            return;

        lock (_cleanupLock)
        {
            if (now < _nextCleanupAt)
                return;

            foreach (var pair in _entries)
            {
                if (pair.Value.ExpiresAt < now)
                    _entries.TryRemove(pair.Key, out _);
            }

            _nextCleanupAt = now.Add(CleanupInterval);
        }
    }
}
